# Generated by Django 4.2.5 on 2023-10-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Test_attempt', models.IntegerField()),
                ('Points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Queid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Que', models.TextField()),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('Ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('Right', models.IntegerField()),
                ('Wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTS_APP.candidate')),
            ],
        ),
    ]
