# Generated by Django 4.2.5 on 2023-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Test_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
